apiVersion: operators.k4indie.io/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  # Sample application deploys an nginx server
  endpoints:
  - domain: demo.k4indie.io
    port: 80
  replicas: 1
  # command: []
  runtime:
    image: nginxdemos/hello
    size: basic

