apiVersion: operators.k4indie.io/v1alpha1
kind: Application
metadata:
  name: application-sample
spec:
  # Sample application deploys an nginx server
  endpoints:
  - port: 9090
  - domain: demo.k4indie.io
    port: 8080
  - domain: savekoin.io
    domain_path: /demo-2
    port: 8080
  replicas: 1
  # command: []
  runtime:
    image: nginxinc/nginx-unprivileged
    size: basic

